import type { Metadata } from "next";
import { raleway } from "@/lib/utils/font";
import "../public/globals.css";
import Navbar from "@/components/Layout/Navbar";
import Providers from "@/lib/utils/providers";
import Footer from "@/components/Layout/Footer";
import Modal from "@/components/Common/Modal";

export const metadata: Metadata = {
  title: "NESA 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Providers>
          {/* <Modal /> */}
          <div className="pb-12">
            <Navbar />
          </div>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
