"use client";

import { useEffect } from "react";
import type { Metadata } from "next";
import { montserrat, poppins } from "@/lib/utils/font";
import "../public/globals.css";
import Providers from "@/lib/providers/providers";
import { AuthProvider } from "@/lib/context/AuthContext";
import Modal from "@/components/UI/Modal"; // Import the Modal component

const metadata: Metadata = {
  title: "NESA 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    // Enable right-click
    // const handleContextMenu = (e: MouseEvent) => e.preventDefault();
    // Enable text selection
    // const handleSelectStart = (e: Event) => e.preventDefault();
    // Enable common keyboard shortcuts (Ctrl+C, Ctrl+S, Ctrl+U, etc.)
    // const handleKeyDown = (e: KeyboardEvent) => {
    //   if (e.ctrlKey && ['c', 's', 'u', 'p'].includes(e.key.toLowerCase())) {
    //     e.preventDefault();
    //   }
    // };

    // Add event listeners
    // document.addEventListener('contextmenu', handleContextMenu);
    // document.addEventListener('selectstart', handleSelectStart);
    // window.addEventListener('keydown', handleKeyDown);

    // Cleanup event listeners on component unmount
    // return () => {
    //   document.removeEventListener('contextmenu', handleContextMenu);
    //   document.removeEventListener('selectstart', handleSelectStart);
    //   window.removeEventListener('keydown', handleKeyDown);
    // };
  }, []);

  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Providers>
            {children}
            <Modal /> {/* Render the Modal globally */}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}