import type { Metadata } from "next";
import { raleway } from "@/lib/utils/font";
import "../public/globals.css";
import Navbar from "@/components/Layout/Navbar";
import Providers from "@/lib/utils/providers";

export const metadata: Metadata = {
  title: "NESA 2023",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
